[tool.poetry]
name = "Gefyra Operator"
version = "1.0.2"
description = "Gefyra Operator runs all cluster-side components of Gefyra's Kubernetes-based development system"
authors = ["Michael Schilonka <michael@blueshoe.io>"]

[tool.poetry.dependencies]
python = "^3.9"
kopf = "^1.36.0"
kubernetes = "^25.3.0"
python-decouple = "^3.7"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2"
black = "^23.1.0"
flake8 = "^6.0.0"
flake8-black = "^0.3.6"
pytest-kubernetes = "^0.2.0"
coverage = "^7.1.0"
pytest-asyncio = "^0.20.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest]
log_cli = true
log_cli_level = "INFO"
norecursedirs = "*.egg .eggs dist build docs .tox .git __pycache__"
addopts = """
	--strict-markers
	--doctest-modules
	--tb=short
	--ignore-glob=main.py
    --ignore-glob=./gefyra/**
"""
testpaths = "tests"