[tool.poetry]
name = "Gefyra Operator"
version = "0.1.0"
description = "Gefyra Operator runs all cluster-side components of Gefyra's Kubernetes-based development system"
authors = ["Michael Schilonka <michael@blueshoe.de>"]

[tool.poetry.dependencies]
python = "^3.8"
kopf = "^1.35.0"
kubernetes = "^19.15.0"
structlog = "^21.3.0"
python-decouple = "^3.5"
toml = "^0.10.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
