# This workflow creates a PR for the formula update

name: Update Homebrew formula

on:
  workflow_dispatch: {}
  workflow_run:
    workflows: ["Build OSX binary"]
    types: [completed]

jobs:
  update_homebrew:
    runs-on: macos-10.15
    if: ${{ github.event.workflow_run.event == 'published' }}
    steps:
    - uses: actions/checkout@v2
    - name: Update Homebrew formula
      working-directory: client/
      env:
        HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.BREW_TOKEN }}
      run: |
        cat pyproject.toml | grep version -m 1 | awk '{ print "APP_VERSION="substr($3, 2, length($3) -2)}' >> $GITHUB_ENV
        brew tap gefyrahq/gefyra
        brew bump-formula-pr --version=${{ env.APP_VERSION }} gefyra
