name: Mac Binary Sanity Check

on:
  workflow_dispatch: {}
  workflow_run:
    workflows: ["Build OSX binary"]
    types: [completed]

jobs:
  sanity_check:
    runs-on: macos-11
    steps:
    - name: Setup Docker and Gefyra
      run: |
        brew install docker
        docker --version
    - name: Download Gefyra from previous workflow
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ${{ github.event.workflow.id }}
        run_id: ${{ github.event.workflow_run.id }}
        workflow_conclusion: success
        name: gefyra-${{ env.APP_VERSION }}-darwin-universal
        path: .
    - name: Sanity run Gefyra
      run: |
        unzip gefyra-${{ env.APP_VERSION }}-darwin-universal.zip
        cd gefyra-${{ env.APP_VERSION }}-darwin-universal/
        chmod u+x ./gefyra
        ./gefyra version
